site_name: FAIR Handbook

theme:
  name: material
  
  features:
  # - navigation.sections
  - navigation.tracking
  - navigation.top
  - toc.follow
  
  palette:
    primary: teal
    accent: teal

  plugins:
  - search
  - tags

  markdown_extensions:
  - attr_list
  - md_in_html

repo_url: https://github.com/nehamoopen/doy-data-guide
repo_name: nehamoopen/doy-fairhandbook
