site_name: DoY Data Guide
site_description: A Data Guide for Dynamics of Youth at Utrecht Univetsity.
site_author: Neha Moopen
site_url: https://nehamoopen.github.io/doy-data-guide

theme:
  name: material
  
  features:
  # - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.follow
  
  palette:
    primary: teal
    accent: teal

plugins:
  - search
  - tags
  - git-revision-date-localized:
      type: iso_datetime

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/nehamoopen/doy-data-guide
repo_name: nehamoopen/doy-data-guide

nav:
  - index.md
  - data-management-planning.md
  - naming-conventions.md
  - folder-structures.md
  - storage-and-backup.md
  - data-collection.md
  - data-pipelining.md
  - data-cleaning.md
  - preregistration.md
  - reproducibility.md
  - reference-management.md
  - codebooks.md
  - metadata.md
  - documentation.md
  - archiving.md
  - publishing.md
  - preprints.md
  - licenses.md
  - file-formats.md
  - data-sharing.md
  - outreach.md
  - fair-assessment-checklists.md

