# Definitions {.unnumbered}

Before diving into the Handbook, it would be good to get familiarized with some data-related terms that are oftentimes misunderstood or used interchangeably.

## Research Data Management

Research Data Management (RDM) refers to the active organization and maintenance of data created during a research project. It is an ongoing activity throughout the data lifecycle, from initial planning to suitable archiving of the data at the project’s completion.

## FAIR Data

The FAIR Data Principles are a set of guiding principles to improve scientific data management and stewardship ([Wilkinson et al., 2016](https://doi.org/10.1038/sdata.2016.18))

- FINDABILITY makes it possible for others to discover your data (metadata, Persistent Identifiers, etc.).
- ACCESSIBILITY makes it possible for humans and machines to gain access to your data, under specific conditions or restrictions where appropriate.
- INTEROPERABILITY ensures data and metadata conform to recognized formats and standards which allows them to be combined and exchanged.
- REUSABILITY requires lots of documentation, which is needed to support data and interpretation and reuse.

## Open Data

Open Data is data that can be freely used, re-used, and redistributed by anyone - subject only, at most, to the
requirement to attribute and share-alike ([Open Data Handbook](https://opendatahandbook.org/guide/en/what-is-open-data/)).

Note that your data does not have to be 'open' to be FAIR! 
Make your data... 'as open as possible, as closed as necessary' ([European Commission](https://ec.europa.eu/research/participants/docs/h2020-funding-guide/cross-cutting-issues/open-access-data-management/data-management_en.htm)).

## Summary

In short,

- RDM = an activity/practice
- FAIR = principles that guide RDM activities/practices
- Open Data = data does not have to be 'open' to be FAIR!