# Searching for Data {.unnumbered}

## What
Instead of creating your own data, you can also search for and re-use existing data. As open science is becoming the standard in academia, more data becomes available at  online repositories scattered across the web. The FAIR principles are aimed at improving the visibility of datasets and facilitating easy re-use of them.

## Why
Searching for existing data can provide multiple benefits during the research life-cycle:
- Using existing data saves time and costs for the researchers
- It allows for a comparison between the existing data and newly generated data
- Inspiration on (improved) research methods can be derived from previous studies
- Learning from other peoples methods can increase data quality

It also poses a disadvantage as the existing data might be in a specific research design, necessitating a rework of your design to make it compatible to your own research question.

## Who

## When


## Where
Data are often put in field specific repositories, registries like [www.re3data.org](Re3Data.org) and [https://fairsharing.org/](FAIRsharing) can help you figure out which repository exists for your field.
At the UU, we also have university wide, generic repositories and catalogues available: [https://dataverse.nl/dataverse/U](DataVerseNL) and [https://www.uu.nl/en/research/yoda](YoDa).
For social sciences and humanities specifically, there are national repositories available under the names of [https://portal.odissei.nl/](ODISSEI) and [https://clariah.nl/ineo/](CLARIAH)

## How
Searching can be done by building queries in the above mentioned repositories, however there are also other options:
- [https://openalex.org/works?page=1&filter=type%3Atypes%2Fdataset](OpenAlex) A database containing a plethora of scientific works, including datasets.
- [https://commons.datacite.org/](DataCite) A large database with the aim of making research available and connected.
- [https://explore.openaire.eu/search/find](OpenAire) and it's Dutch counterpart [https://netherlands.openaire.eu/](Netherlands Research Portal)
- [https://data.europa.eu/en](Open Data Europe) Has a large collection of European datasets both EU and beyond.


## References
[https://www.uu.nl/en/research/research-data-management/tools-services/finding-existing-data](https://www.uu.nl/en/research/research-data-management/tools-services/finding-existing-data)
[https://dmeg.cessda.eu/Data-Management-Expert-Guide/7.-Discover/The-process-of-data-discovery](https://dmeg.cessda.eu/Data-Management-Expert-Guide/7.-Discover/The-process-of-data-discovery)
[https://rdm.vu.nl/topics/finding-existing-data.html](https://rdm.vu.nl/topics/finding-existing-data.html)