# Data Sharing {.unnumbered}

When sharing (personal) data with collaborators outside the university, there are a couple of important considerations:

- The participation letter and informed consent forms should have clearly informed participants about data sharing and reuse + they should agree to it.
- A Data Protection Impact Assessment may have to be carried out, this will reveal to what extent it is safe to share data (or not) and how that can be put into practice (for example, pseudonymization techniques)
- Any transfer of data outside the UU will require a Data Transfer Agreement in line with the GDPR, the complexity of the DTA will vary depending on the nature of the transfer (for example, transfer outside the EU).

## Tools

### SURFfilesender

SURFFileSender is a reliable tool to send data to another user. You can send large files securely and the option for encryption makes it more safe.

### Virtual Research Environments

VREs, for example - AnDREa & ResearchCloud, is a temporary computing environment that is secure and contains the necessary tools and files for users to carry out some research activities.

